### PR TITLE
Add support for basemaps.

### PR DESCRIPTION
**Pull request by pkaminski**
This change is [Reviewable](https://reviewable.io/reviews/reviewable/enterprise-tools/7)

### CODE REVIEW

**Comment by pkaminski** [comment]
+reviewer:@earlachromatic

**Review by earlAchromatic — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/enterprise-tools/7#-:-NECLE4ZBTiaH8m5bcUu:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @pkaminski)

___
*[`extract_data.js` line 314 at r1](https://reviewable.io/reviews/reviewable/enterprise-tools/7#-NECKySdDLzcxvTGnAsf:-NECKySdDLzcxvTGnAsg:b-k7f50p) ([raw file](https://github.com/reviewable/enterprise-tools/blob/f130d2cc36502eb570b342c4951e2df39c12045d/extract_data.js#L314)):*
> ```JavaScript
>   log('Extracting basemaps');
>   await forEachLimit(reviewKeys, 25, async reviewKey => {
>     const filemap = await db.child('basemaps/:reviewKey', {reviewKey}).get();
> ```

Minor: would have expected this const to be called basemaps following the pattern in the above functions.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/enterprise-tools/7)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @earlAchromatic)

___
*[`extract_data.js` line 314 at r1](https://reviewable.io/reviews/reviewable/enterprise-tools/7#-NECKySdDLzcxvTGnAsf:-NEE5rez-xxLDxDj2y_7:b17t7ul) ([raw file](https://github.com/reviewable/enterprise-tools/blob/f130d2cc36502eb570b342c4951e2df39c12045d/extract_data.js#L314)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

Minor: would have expected this const to be called basemaps following the pattern in the above functions.
</blockquote></details>

Remember kids, don't rush too much when copy-pasting code!  Fixed.  :)

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/enterprise-tools/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
